name: control_c
description: Aplicativo para registrar gastos com combustívels, app básico que visa aprimorar técnicas na linguagem de programação Flutter testar funcionalidades.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.1
  intl: ^0.17.0
  path: ^1.8.0
  flutter_slidable: ^1.1.0
  rounded_loading_button: ^2.0.8
  splash_screen_view: ^3.0.0
  flutter_native_splash: ^1.3.2
  another_flushbar: ^1.10.28

  cupertino_icons: ^1.0.2

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"

flutter:

  uses-material-design: true

  assets:
    - assets/images/icon.png
